version: '2'
services:
  ros-master:
    image: gramaziokohler/ros-base:latest
    container_name: ros-master
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: augmentedfabricationlab/ros-abb-planner-fabtory:latest
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch

  ros-fileserver:
    image: augmentedfabricationlab/ros-abb-planner-fabtory:latest
    container_name: ros-fileserver
    environment:
      - ROS_HOSTNAME=ros-fileserver
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - file_server
      - file_server.launch

  abb-demo:
    image: augmentedfabricationlab/ros-abb-planner-fabtory:latest
    container_name: abb-fabtory-demo
    environment:
      - ROS_HOSTNAME=abb-demo
      - ROS_MASTER_URI=http://ros-master:11311
      - DISPLAY=gui:0.0
    depends_on:
      - ros-master
      - gui
    command:
      - roslaunch
      - --wait
      - abb_fabtory_moveit_config
      - demo.launch

  gui:
    image: gramaziokohler/novnc:latest
    container_name: abb-fabtory-gui
    ports:
      - "8080:8080"


  abb-driver:
    image: compasrrc/compas_rrc_driver:v1.1.0
    container_name: abb-driver
    environment:
    - ROS_HOSTNAME=abb-driver
    - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
    - ros-master
    command:
    - roslaunch
    - --wait
    - compas_rrc_driver
    - bringup.launch
    - robot_ip:=host.docker.internal
    - robot_streaming_port:=30101
    - robot_state_port:=30201
    - namespace:=rob1
